sudo: required

services:
  - docker

before_install:
- docker pull blang/latex:ubuntu

script:
- docker run -v "$PWD":/data blang/latex:ubuntu pdflatex main.tex
- mkdir pdf
- mv main.pdf pdf/out.pdf

deploy:
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
