sudo: required

services:
  - docker

before_install:
- docker pull blang/latex:ubuntu

script:
- docker run -v "$PWD":/data blang/latex:ubuntu pdflatex main.tex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages
